### ISSUE TITLE
处理OpaquePointer的方式是错误/不合规的

### ISSUE THREAD

**Issue by Naville** [NeHyci/Hikari-LLVM15#1]
``-mllvm -opaque-pointers=false -Xclang -no-opaque-pointers``
否则CFE的CodeGen走的还是OpaquePointer
同步更新到了 https://github.com/HikariObfuscator/Hikari/issues/102

**Comment by NeHyci** [comment]
关于处理OpaquePointers，我一开始是打算根据[](https://llvm.org/docs/OpaquePointers.html) 把getPointerElementType()的调用都替换成他里面所写的，但是测试后StringEncryption编译会报错，也看不懂是哪里的问题
```
error: Don't know how to promote fpowi to fpow
```
然后我在这个网页我往下翻看到了这些：
```
For users of LLVM as a library, opaque pointers can be disabled by calling setOpaquePointers(false) on the LLVMContext.
```
所以我使用了这个方法，编译后也确实能正常工作

**Comment by NeHyci** [comment]
在```Obfuscation::runOnModule(Module &M)```，所有混淆完毕后会重新把Context的OpaquePointers设置为true

**Comment by Naville** [comment]
> error: Don't know how to promote fpowi to fpow
看着是后端CodeGen的问题? 完整的StackTrace可以看一下.
> 所以我使用了这个方法，编译后也确实能正常工作，我并不理解为什么这是错误/不合规的
是的，你的理解没错，用LLVM库的话可以用这个方式Disable. 但是Clang也是LLVM库的user, 所以不去Patch Clang的话会导致Clang的CodeGen继续按照OpaquePointer来实现, 而混淆按照NonOpaquePointer来Transform， 而这至少以我个人的经验听起来不是个好主意, 尤其是如果后续增加更多Pass的话, 可能会影响其他Pass的Assumption

**Comment by Naville** [comment]
正确的Disable其实也只需需要Patch源码的两处地方, 你本身就是整个LLVM的源码分发, 其实并不影响

**Comment by Naville** [comment]
我在Hikari原来的issue里面更新了两个链接, 是源码层默认禁用掉OpaquePointer的至少我认为正确的方式. 供参考

**Comment by NeHyci** [comment]
我会创建一个opaque pointers默认关闭的branch

**Comment by google-mirror** [comment]
为啥要禁用

**Comment by NeHyci** [comment]
> 为啥要禁用

如果不禁用，一些功能不能正常使用，因为没有兼容Opaque Pointer

**Comment by NeHyci** [comment]
> > 为啥要禁用
> 
> 如果不禁用，一些功能不能正常使用，因为没有兼容Opaque Pointer

已经在[https://github.com/NeHyci/Hikari-LLVM15/commit/0a53037f688487e30de13669f22493f412e35372](https://github.com/NeHyci/Hikari-LLVM15/commit/0a53037f688487e30de13669f22493f412e35372)完全支持了Opaque Pointers

**Comment by G5t4r** [comment]
大佬牛逼，请教下如何学习LLVM和混淆pass开发呢？

**Comment by NeHyci** [comment]
> 大佬牛逼，请教下如何学习LLVM和混淆pass开发呢？

我也不太明白

**Comment by G5t4r** [comment]
> > 大佬牛逼，请教下如何学习LLVM和混淆pass开发呢？
> 
> 我也不太明白

能给个联系方式么，遇到一个bug，直接发你demo
