### ISSUE TITLE
String encryption don't seem to work

### ISSUE THREAD

**Issue by medievalghoul** [NeHyci/Hikari-LLVM15#13]
I added the flags `-Xllvm -enable-strcry -Xllvm -strcry-encrypt-global-string` in the *Other Swift Flags* of Xcode; however, it don't seem to make a change with the IOS app. 

```
juliusalexandre@Juliuss-MacBook-Pro testing-obf.app % strings testing-obf

...
Body
Previews
Body
ContentView
ContentView_Previews
$s11testing_obf11ContentViewV4bodyQrvp
$s11testing_obf20ContentView_PreviewsV8previewsQrvpZ
testing_obf
testing_obfApp
$s11testing_obf0a1_B3AppV4bodyQrvp
globe
Hello, world!
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>application-identifier</key>
<string>TCKTXXK9UU.test.testing-obf</string>
</dict>
</plist>
;09

application-identifier

```

is there any reason why this is happening?

**Comment by NeHyci** [comment]
Have you tried "Clean Build Folder" before building?

**Comment by medievalghoul** [comment]
> Have you tried "Clean Build Folder" before building?

Thanks for the reply and yes I did a "Clean Build Folder", it didn't change much. Is there anything I need to do to the Build Settings of xcode? I'm in debug mode.

**Comment by NeHyci** [comment]
Other than Optimization Level and Custom Flag, you should not need to do much with the Build Settings of Xcode. I'm not sure what's going on, can you upload your xcode project？

**Comment by medievalghoul** [comment]
Sorry for the late reply, but here's the xcode project 
[t1.zip](https://github.com/NeHyci/Hikari-LLVM15/files/9847490/t1.zip)

**Comment by NeHyci** [comment]
> Sorry for the late reply, but here's the xcode project 
> 
> [t1.zip](https://github.com/NeHyci/Hikari-LLVM15/files/9847490/t1.zip)
> 
> 

On my Xcode, StringEncryption works great on this project. Maybe there are some problems with your Hanabi installation?

**Comment by medievalghoul** [comment]
> On my Xcode, StringEncryption works great on this project. Maybe there are some problems with your Hanabi installation?

I'm assuming that's the case, because when I run the `swiftc` in the command line, I get this 
```
juliusalexandre@Julius-MacBook-Pro LearningTime % swiftc simple.swift                     
Applying Apple Clang Hooks...
Initializing Hikari Core with Revision ID:
Applying Apple SwiftC Hooks...
std::mt19937_64 seeded with current timestamp: 1666618184832
Failed To Link PreCompiled AntiHooking IR From:/Users/juliusalexandre/Hikari/PrecompiledAntiHooking-unknown-unknown.bc
Failed To Loading Symbol Configuration From:/Users/juliusalexandre/Hikari/SymbolConfig.json
Doing Post-Run Cleanup
Hikari Out
```

**Comment by medievalghoul** [comment]
Is there any way i can fix this `Symbol Configuration` and `PreCompiled AntiHooing` issue? I can't seem to find anything on the original git repo

**Comment by NeHyci** [comment]
> Is there any way i can fix this `Symbol Configuration` and `PreCompiled AntiHooing` issue? I can't seem to find anything on the original git repo

You can find examples of them at https://github.com/HikariObfuscator/Resources

**Comment by medievalghoul** [comment]
Everything works fine now, I uninstalled (unload) the .dylib and I reinstalled it with the latest .dylib's as of now  [Hanabi_for_Xcode-14.0.1_20221030-2](https://github.com/NeHyci/Hanabi/releases/download/Xcode-14/Hanabi_for_Xcode-14.0.1_20221030-2.7z)
