### ISSUE TITLE
Hanabi does not work properly on macOS Ventura

### ISSUE THREAD

**Issue by NeHyci** [NeHyci/Hikari-LLVM15#14]
substitute is not compatible with macOS Ventura.

**Comment by NeHyci** [comment]
Fixed by using Dobby instead of substitute.

**Comment by malhaar** [comment]
@NeHyci hanabi working with macos ventura and xcode 14.0.1 ? also any eta on update for xcode 14.1?

**Comment by NeHyci** [comment]
I didn't test Hanabi with Dobby on MacOS Ventura, but I was told that Hanabi with Dobby worked on MacOS Ventura. 
Hanabi in the current Releases works normally in Xcode14.1.
