### ISSUE TITLE
Hanabi Build Instructions

### ISSUE THREAD

**Issue by malhaar** [NeHyci/Hikari-LLVM15#15]
Can you please post building instructions for Hanabi? (Step By Step if possible **** PLEASE ****) i am trying to learn this project.

when i run this ..
"cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF /Volumes/Development/Hikari/llvm/projects"

I Get Error..
`CMake Error at CMakeLists.txt:5 (add_dependencies):
  The dependency target "LLVMCore" of target "LLVMHanabiDeps" does not exist.

CMake Error at CMakeLists.txt:5 (add_dependencies):
  The dependency target "LLVMPasses" of target "LLVMHanabiDeps" does not
  exist.

CMake Error at CMakeLists.txt:5 (add_dependencies):
  The dependency target "LLVMSupport" of target "LLVMHanabiDeps" does not
  exist.

CMake Error at CMakeLists.txt:17 (add_dependencies):
  The dependency target "LLVMObfuscation" of target "LLVMHanabi" does not
  exist.`

Regards,
M

**Comment by xybp888** [comment]
cd llvm/build 
run: cmake "-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64" -DCMAKE_BUILD_TYPE=Release -DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF -G Ninja ../
ninja LLVMHanabi

**Comment by malhaar** [comment]
> cmake "-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64" -DCMAKE_BUILD_TYPE=Release -DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF -G Ninja ../
> ninja LLVMHanabi

Received Error ->
-- Build files have been written to: /Volumes/Development/Hikari/llvm/build
ninja: error: unknown target 'LLVMHanabi'

**Comment by malhaar** [comment]
For anyone looking for steps to build hanabi .. 

1. git clone --recursive -b llvm-15.0.2rel https://github.com/NeHyci/Hikari-LLVM15.git Hikari && cd Hikari && git submodule update --remote --recursive
2. cd llvm 
3. mkdir build
4. cd build
5. cmake -G Ninja "-DCMAKE_OSX_ARCHITECTURES=arm64" -DCMAKE_BUILD_TYPE=Release -DLLVM_ABI_BREAKING_CHECKS=FORCE_OFF ../
6. ninja LLVMHanabi
