### ISSUE TITLE
Hanabi stopped working on Monterey 12.6 

### ISSUE THREAD

**Issue by malhaar** [NeHyci/Hikari-LLVM15#17]
This release https://github.com/NeHyci/Hanabi/releases/download/Xcode-14/Hanabi_for_Xcode-14.0.1_20221030-2.7z stopped working on Monterey 12.6 and XCode 14.0.1 i had to revert to old release.

**Comment by NeHyci** [comment]
Can you screenshot the error you encountered? What is the CPU architecture of your Mac?

**Comment by medievalghoul** [comment]
What error are you encountering for it to stop working?

**Comment by malhaar** [comment]
there is no error or anything compilation completes fine, it just doesn't do anything. SS attached.

<img width="1191" alt="Screen Shot 2022-10-31 at 12 54 51 PM" src="https://user-images.githubusercontent.com/392704/199064872-14da902d-a86a-48d9-a885-71bc2cd0123e.png">

My observations. 
i used -mllvm -enable-bcfobf -mllvm -enable-cffobf -mllvm -enable-strcry -mllvm -enable-funcwra it does nothing.
- compilation speed is pretty fast, build times are like when you are not using hikari.
- binary size is back to normal, i opened in ida shows no obfuscation.

**Comment by malhaar** [comment]
> That's the same thing that happened to me, I can't seem to find a fix for it

i reverted to Hanabi_for_Xcode-14.0_and_14.0.1_20221006.7z

**Comment by malhaar** [comment]
hello there, looks like issues is when using xcode with rosetta on m1, may be i enabled it long time ago and forgot about it. i disabled open using rosetta on xcode.app and now latest release is working fine.

But surprisingly 1st build works fine in either case.

Regards,
M
