### ISSUE TITLE
当使用-mllvm -enable-cffobf时， 报错Internal error: atom is missing a symbolIndex

### ISSUE THREAD

**Issue by xxzzddxzd** [NeHyci/Hikari-LLVM15#18]
您好
我在编译时发现，混淆指令除去-mllvm -enable-cffobf时，不会报错且app正常运行。加上-mllvm -enable-cffobf后，会有报错
ld: internal error: atom is missing a symbolIndex(_objc_msgSend$appendFormat:) for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

环境：
mac mini m1，xcode 14.0.1，使用hanabi中的release

**Comment by NeHyci** [comment]
Xcode的LLVM套件有大量的定制处理，所以Hanabi可能出现一些奇怪的问题，我并不清楚如何修复，如果不是有特殊需求，尽量不要使用Hanabi

**Comment by xxzzddxzd** [comment]
谢谢，我尝试一下toolchain的方式。
之前我使用apple/swift的build-toolchain，编译出来的工具链在arm mac下有各种问题，项目甚至出现无法正常编译的情况。
如果可以的话您能分享一个完整的toolchain吗？

**Comment by NeHyci** [comment]
> 之前我使用apple/swift的build-toolchain，编译出来的工具链在arm mac下有各种问题，项目甚至出现无法正常编译的情况。

试试[https://github.com/NeHyci/Hikari-Swift](https://github.com/NeHyci/Hikari-Swift)
