### ISSUE TITLE
functions annotations not work

### ISSUE THREAD

**Issue by oooio** [NeHyci/Hikari-LLVM15#19]
source:
<img width="580" alt="CleanShot 2022-11-07 at 13 39 02@2x" src="https://user-images.githubusercontent.com/64519482/200234320-70c52fdf-3fa8-4d85-b79d-723fca53214d.png">
dis:
<img width="738" alt="CleanShot 2022-11-07 at 13 39 33@2x" src="https://user-images.githubusercontent.com/64519482/200234366-034b22d2-f60b-4f12-8040-18d5ba3d48a4.png">

**Comment by oooio** [comment]
I have read the guide
https://github.com/HikariObfuscator/Hikari/wiki/Functions-Annotations

**Comment by oooio** [comment]
clang version 15.0.2 (https://github.com/NeHyci/Hikari-LLVM15 0f6d5c327e6476de9096598c5d5bf7cef062e083)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
Xcode Version 13.1 (13A1030d)

**Comment by NeHyci** [comment]
In fact, it works. This issue is wrong
