### ISSUE TITLE
building on macOS

### ISSUE THREAD

**Issue by NewDwarf** [NeHyci/Hikari-LLVM15#24]
Did you try to build the latest snapshot on macOS Monterey?
I have faced with couple of build issues

First issue:
```
Hikari-LLVM15/llvm/lib/Transforms/Obfuscation/FunctionCallObfuscate.cpp:5:
Hikari-LLVM15/llvm/include/llvm/Transforms/Obfuscation/compat/CallSite.h:130:45: error: no member named 'getElementType' in 'llvm::PointerType'
    assert(cast<PointerType>(V->getType())->getElementType() ==
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
```

The second issue:
```
Hikari-LLVM15/llvm/lib/Transforms/Obfuscation/StringEncryption.cpp:394:11: error: 'llvm::Triple' is an incomplete type
      if (Triple(GV->getParent()->getTargetTriple()).isArm64e()) {
          ^

```
For this issue you have to add 
`#include "llvm/ADT/Triple.h"`
in the Hikari-LLVM15/llvm/lib/Transforms/Obfuscation/StringEncryption.cpp

**Comment by NeHyci** [comment]
I will check it...

**Comment by Naville** [comment]
It's ``PointerType::getNonOpaquePointerElementType`` in LLVM15 due to opaque pointer changes @NeHyci

**Comment by NeHyci** [comment]
should be fixed in [https://github.com/NeHyci/Hikari-LLVM15/commit/f8181814adc34e4cea816676a2b86f3fa7e1e685](https://github.com/NeHyci/Hikari-LLVM15/commit/f8181814adc34e4cea816676a2b86f3fa7e1e685)

**Comment by NeHyci** [comment]
> It's ``PointerType::getNonOpaquePointerElementType`` in LLVM15 due to opaque pointer changes @NeHyci

I checked the CallBase::setCalledFunction in LLVM15, it uses PointerType::isOpaqueOrPointeeTypeMatched.

**Comment by Naville** [comment]
> > It's `PointerType::getNonOpaquePointerElementType` in LLVM15 due to opaque pointer changes @NeHyci
> 
> I checked the CallBase::setCalledFunction in LLVM15, it uses PointerType::isOpaqueOrPointeeTypeMatched.

Depends on whether you just need the type, or you need equality check.
Anyway, getElementType() is scheduled for removal soon
