### ISSUE TITLE
Porting on Apple clang (question)

### ISSUE THREAD

**Issue by NewDwarf** [NeHyci/Hikari-LLVM15#27]
What is the best option to port/backport this project on the Apple clang?
Suppose I have
```
bash-3.2$ clang -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
I tried to find the source code for clang-1400.0.29.202 but I was not able to do it. Not sure the source codes are available.
If they are not available how can I do integration with Hikari?

**Comment by NeHyci** [comment]
[https://github.com/apple/llvm-project](https://github.com/apple/llvm-project)

**Comment by NewDwarf** [comment]
> https://github.com/apple/llvm-project

Thanks! Do you know how to sync the source tree snapshot in the `apple/llvm-project` repository with the llvm/clang version to be installed. In my case, it is `Apple clang version 14.0.0 (clang-1400.0.29.202)`

**Comment by NeHyci** [comment]
> > https://github.com/apple/llvm-project
> 
> 
> 
> Thanks! Do you know how to sync the source tree snapshot in the `apple/llvm-project` repository with the llvm/clang version to be installed. In my case, it is `Apple clang version 14.0.0 (clang-1400.0.29.202)`
> 
> 
> 
> Probably, the branch `stable/20221013` is an option. According to its name, it was created Oct 13 2022. But the Xcode 14.1 based on the clang-1400.0.29.202 was released on Nov 1 2022.

I have no idea.

**Comment by NewDwarf** [comment]
The `stable/20211026` branch gives
```
clang version 14.0.0 (https://github.com/apple/llvm-project.git c33f34f65cd5eda385964c4176906d55d7236206)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
```
The branch `stable/20221013` is LLVM 15.
The thing is not clear is the clang output looks like a generic LLVM but at the same time this branch has Apple's patches.

**Comment by NeHyci** [comment]
The LLVM that Apple uses in Xcode does not seem to be open source, such as the "ptrauth.abi-version" flag in the generated Module when the target is set to arm64e in the LLVM of Xcode, but we can't find any trace of it in the Apple's fork of LLVM.
