### ISSUE TITLE
Are -enable-cffobf and -enable-indibran mutual excluding parameters?

### ISSUE THREAD

**Issue by NewDwarf** [NeHyci/Hikari-LLVM15#32]

**Comment by NewDwarf** [comment]
When I tries to use -enable-cffobf and -enable-indibran parameters together, I don't get indirect branch obfuscation although I still have the branch instructions between basic blocks but they are not replaced on the indirect branch instructions,

**Comment by NeHyci** [comment]
[https://github.com/NeHyci/Hikari-LLVM15/commit/7d5d15858927ea1bdc219130a5801d89a1b43154](https://github.com/NeHyci/Hikari-LLVM15/commit/7d5d15858927ea1bdc219130a5801d89a1b43154)

**Comment by Naville** [comment]
> 7d5d158

That's a....really stupid implementation for hopefully very obvious reasons

**Comment by NeHyci** [comment]
> > 7d5d158
> 
> 
> 
> That's a....really stupid implementation for hopefully very obvious reasons

I'm sorry that I haven't thought of another solution yet.

**Comment by Naville** [comment]
> > > [7d5d158](https://github.com/NeHyci/Hikari-LLVM15/commit/7d5d15858927ea1bdc219130a5801d89a1b43154)
> > 
> > 
> > That's a....really stupid implementation for hopefully very obvious reasons
> 
> I'm sorry that I haven't thought of another solution yet.

LowerSwitch exists in today's LLVM , you just need a PM to run it with
