### ISSUE TITLE
Register the obfuscation pass as a llvm pass plugin

### ISSUE THREAD

**Issue by NeHyci** [NeHyci/Hikari-LLVM15#33]
The entire LLVM source code may be too heavy.

**Comment by NewDwarf** [comment]
Can we control plugin insertion into the pass pipeline? 
What is the strategy to choose the place where to invoke the specific plugin based llvm pass? 
Before the specific optimization or after, or just on pipeline entry?

**Comment by Naville** [comment]
https://discourse.llvm.org/t/fyi-llvm-project-repo-has-exceeded-github-upload-size-limit/63293

FYI
