### ISSUE TITLE
-acd-rename-methodimp这个参数如何使用

### ISSUE THREAD

**Issue by LanBaiCode** [NeHyci/Hikari-LLVM15#36]
这个参数是要配置一下要混淆的函数名称吗？我使用了这个参数，编译完后在IDA里边看了下，发现还是原来的函数名称并没有被替换成ACDMethodIMP

**Comment by NeHyci** [comment]
这是替换被AntiClassDump混淆的OC方法的函数名称，不是所有函数

**Comment by LanBaiCode** [comment]
> 这是替换被AntiClassDump混淆的OC方法的函数名称，需要启用AntiClassDump，不是所有函数

有什么参数能够自动混淆函数、变量的名称吗

**Comment by Naville** [comment]
你知道在编译器层尤其是SingleTU的编译模式下做符号和OC方法重命名是件很蠢的事情对吧

**Comment by NeHyci** [comment]
> 你知道在编译器层尤其是SingleTU的编译模式下做符号和OC方法重命名是件很蠢的事情对吧

这个东西只是重命名OC方法的符号，我个人感觉大多数情况下不会有什么问题，搞这个主要是考虑到有的人可能懒得strip符号

**Comment by Naville** [comment]
> > 你知道在编译器层尤其是SingleTU的编译模式下做符号和OC方法重命名是件很蠢的事情对吧
> 
> 这个东西只是重命名OC方法的符号，并不是更改方法名，我个人感觉一般情况下不会有什么问题，搞这个主要是考虑到有的人可能懒得strip符号

我知道, 我的意思是他可能想找的就是改方法名和C函数
