### ISSUE TITLE
AntiHooking缺少ir文件

### ISSUE THREAD

**Issue by qwemnbvv** [NeHyci/Hikari-LLVM15#37]
Failed To Link PreCompiled AntiHooking IR From:/home/Hikari/PrecompiledAntiHooking-unknown-unknown.bc
不会影响使用吗

**Comment by NeHyci** [comment]
readme写了

**Comment by qwemnbvv** [comment]
在哪里呢
这是匹配整个项目的字符
/data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/llvm/lib/Transforms/Obfuscation/AntiHooking.cpp:    Function *AHCallBack = M->getFunction("AHCallBack");
/data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/llvm/lib/Transforms/Obfuscation/AntiHooking.cpp:    if (AHCallBack) {
/data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/llvm/lib/Transforms/Obfuscation/AntiHooking.cpp:      IRBB->CreateCall(AHCallBack);
/data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/README.md:支持检测Objective-C运行时Hook。如果检测到就会调用AHCallBack函数(从PreCompiled IR获取)，如果不存在AHCallBack，就会退出程序。
/data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/README.md:InlineHook检测目前只支持ARM64平台。自动在函数中插入代码检测当前函数是否被Hook(通过判断BR X16和BR X17实现)，如果检测到就会调用AHCallBack函数(从PreCompiled IR获取)，如果不存在AHCallBack，就会退出程序。
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/lib/Transforms/Obfuscation/CMakeFiles/LLVMObfuscation.dir/AntiHooking.cpp.o matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/lib/libLLVMObfuscation.a matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/lib/libclang-cpp.so matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/lib/libLTO.so.15 matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/lib/libLTO.so matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/lib/libclang-cpp.so.15 matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/llvm-lto matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/llc matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/clang-repl matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/bugpoint matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/clang matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/clang-scan-deps matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/llvm-lto2 matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/clang++ matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/clang-cl matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/clang-15 matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/clang-cpp matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/opt matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/llvm-opt-fuzzer matches
Binary file /data/data/com.termux/files/home/Hikari-LLVM15-llvm-15.0.2rel/Hikari-LLVM15-llvm-15.0.2rel/build/bin/clang-linker-wrapper matches
还是需要从其他地址获取

**Comment by qwemnbvv** [comment]
或者有其他的名字吗

**Comment by NeHyci** [comment]
ir文件是让你自己自定义，如果没有会怎么样都已经写出来了

**Comment by Naville** [comment]
https://github.com/HikariObfuscator/Resources
这里是2017年的实现, 放在现代的LLVM版本大概率是编译不起来的, 但你可以自己照着重新实现

**Comment by Naville** [comment]
@NeHyci 这里文档我感觉可以补一下? 提示用户自己写Callback然后``-S -emit-llvm``
