### ISSUE TITLE
AntiHooking: support detect arm64 near branch trampoline and software breakpoint InlineHook

### ISSUE THREAD

**Issue by NeHyci** [NeHyci/Hikari-LLVM15#38]
arm64 near branch trampoline: [https://github.com/jmpews/Dobby/blob/master/source/InterceptRouting/RoutingPlugin/NearBranchTrampoline/near_trampoline_arm64.cc](https://github.com/jmpews/Dobby/blob/master/source/InterceptRouting/RoutingPlugin/NearBranchTrampoline/near_trampoline_arm64.cc)

arm64 software breakpoint: [https://github.com/evelyneee/ellekit/blob/main/ellekit/Languages/C/Hook.swift](https://github.com/evelyneee/ellekit/blob/main/ellekit/Languages/C/Hook.swift)

**Comment by NeHyci** [comment]
Maybe we just need to check that the first instruction of a function is correct, not that the first few instructions of a function are some kind of InlineHook Trampoline.

**Comment by NeHyci** [comment]
Automatic detection of instruction types may be possible through the LLVM Machine Code JIT.

**Comment by NeHyci** [comment]
> With LLVM Machine Code JIT, we may be able to automatically detect instruction types at the IR level, which is just a guess.

I ran some tests, and I can confirm that it works.

**Comment by NewDwarf** [comment]
Could you, please, briefly describe what problem should cover this solution?
Thanks.

**Comment by NeHyci** [comment]
> Could you, please, briefly describe what problem should cover this solution?
> Thanks.

I'm not sure I know what you mean.

**Comment by NeHyci** [comment]
[https://github.com/NeHyci/Hikari-LLVM15-Core/commit/dd3fd8cd24b5310aea56180b8243168f5e37acea](https://github.com/NeHyci/Hikari-LLVM15-Core/commit/dd3fd8cd24b5310aea56180b8243168f5e37acea)
