### ISSUE TITLE
AntiHooking: sometimes asm generated by MCJIT is different from asm generated by static compilation

### ISSUE THREAD

**Issue by NeHyci** [NeHyci/Hikari-LLVM15#39]
Do not know how to solve it, may fall back on the old implementation

**Comment by Naville** [comment]
Backend Passes

**Comment by NeHyci** [comment]
> Backend Passes

How do I make MCJIT the same as Backend Passes run by static compilation?

**Comment by Naville** [comment]
No MCJIT involved, just don't use MCJIT

**Comment by Naville** [comment]
MCJIT doesn't guarantee to run the same compilation pipeline, so your design is inherently broken

**Comment by NeHyci** [comment]
Ok, so all I need to do is just go back to the old implementation.

**Comment by Naville** [comment]
Or write backend pass, depends on your spare time available

**Comment by Naville** [comment]
[llvm/lib/Target/AArch64/AArch64TargetMachine.cpp](https://github.com/llvm/llvm-project/blob/ae691c381261311c4ae2697fc5b1ae2e2113ca6c/llvm/lib/Target/AArch64/AArch64TargetMachine.cpp#L796) is where you should be looking

**Comment by Naville** [comment]
I personally suggests you start poking with it, because:
- Knowledge only w.r.t. MiddleEnd isn't going anywhere for a actual production grade obfuscation, I've personally submitted multiple backend bug reports/ bug fixes, with more pending.
- AntiHook is indeed best implement in the backend

**Comment by NeHyci** [comment]
Thank you for your advice, if I have enough time, I will try to study this.
