### ISSUE TITLE
how to build

### ISSUE THREAD

**Issue by Reijaff** [NeHyci/Hikari-LLVM15#4]
tried to compile https://github.com/NeHyci/Hikari-LLVM15/tree/llvm-15.0.0rel-disable-opaque-pointers 
with 
cmake -S llvm -B build -G "Ninja" -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_APPEND_VC_REV=on
got compilation error
can you share your build flags?

**Comment by NeHyci** [comment]
```
mkdir build
cd build
cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_CREATE_XCODE_TOOLCHAIN=ON -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;compiler-rt" -DLLVM_INCLUDE_TESTS=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DLLVM_INCLUDE_EXAMPLES=OFF ../llvm
```
