### ISSUE TITLE
编译头文件报错，要手动修复吗？

### ISSUE THREAD

**Issue by fly8888** [NeHyci/Hikari-LLVM15#41]
<img width="1098" alt="iShot_2023-02-27_10 53 25" src="https://user-images.githubusercontent.com/24579378/221462238-325a986d-0979-4879-a14c-3455c93b432c.png">

**Comment by Naville** [comment]
看着是缺头文件?

**Comment by Naville** [comment]
这个.cpp里加一下:
```
#include <llvm/Support/CommandLine.h>
```
对应的头文件加:
```
#include <llvm/PassRegistry.h>
```

**Comment by fly8888** [comment]
在 Hikari/llvm/include/llvm/IR/PassManager.h 文件
增加 以下头文件 解决了
`
#include <llvm/PassRegistry.h>
#include "llvm/Pass.h"
#include <llvm/Support/CommandLine.h>
#include <map> 
`

**Comment by NeHyci** [comment]
LLVM15需要引用的头文件比llvm14要多，我忘了在
llvm15上测试了。

现在应该已经修好了
