### ISSUE TITLE
repo to build swift toolchain (question)

### ISSUE THREAD

**Issue by NewDwarf** [NeHyci/Hikari-LLVM15#43]
What repo is main to build the swift compiler which supports obfuscation?
I noticed that there is a branch https://github.com/NeHyci/Hikari-LLVM15/tree/llvm-swift-5.7.2-RELEASE
and there is the separated repo https://github.com/NeHyci/Hikari-Swift/tree/master

Which one should we use?

**Comment by NeHyci** [comment]
only need to run the ```https://github.com/NeHyci/Hikari-Swift/tree/master``` provided in the command
