### ISSUE TITLE
Use cases of the ConstantEncryption protection

### ISSUE THREAD

**Issue by NewDwarf** [NeHyci/Hikari-LLVM15#47]
What are the use cases for the ConstantEncryption protection?
I didn't studied this protection yet but I just played with different values. Each case produces the integer values in the plain text in the disassembly listing.
For example, I tried such sample code

```
unsigned int a = 0x11223344;
const unsigned int b = 0x55667788;
static unsigned int c = 0x99aabbcc;
static const unsigned int d = 0xddeeff00;

int main()
{
    unsigned int a_loc = 0x12345678;
    const unsigned int b_loc = 0x9abcdef0;
    printf("%08X, %08X, %08X, %08X, %08X, %08X", a, b, c, d, a_loc, b_loc);

    return 0;
}
```

And I got below decompiled output which clearly show that all integers are in plain text:
```
int __cdecl main(int argc, const char **argv, const char **envp)
{
  printf(
    "%08X, %08X, %08X, %08X, %08X, %08X",
    0x11223344LL,
    0x55667788LL,
    0x99AABBCCLL,
    0xDDEEFF00LL,
    0x12345678LL,
    0x9ABCDEF0LL);
  return 0;
}
```

**Comment by NeHyci** [comment]
Add -mllvm -constenc_togv to cflag and you can see the difference

**Comment by NewDwarf** [comment]
Yes, the difference is noticeable:
```
int __cdecl main(int argc, const char **argv, const char **envp)
{
  printf(
    "%08X, %08X, %08X, %08X, %08X, %08X",
    0x11223344LL,
    dword_3A98 ^ (unsigned int)dword_3A94,
    dword_3A8C ^ dword_3A90 ^ 0x5CC3A60Bu,
    dword_3AA0 ^ (unsigned int)dword_3A9C,
    dword_3A80 ^ (unsigned int)dword_3A7C,
    dword_3AA8 ^ (unsigned int)dword_3AA4);
  return dword_3AB0 ^ dword_3AAC;
}
```

...but the global, non-const variable (`unsigned int a = 0x11223344;`) is not obfuscated. Is it expected behavior?

**Comment by NeHyci** [comment]
> ...but the global, non-const variable (`unsigned int a = 0x11223344;`) is not obfuscated. Is it expected behavior?

no, this is because the default value of -mllvm -constenc_prob is 60. If you want to encrypt all constants, you need to set it to 100

**Comment by NewDwarf** [comment]
Forgot to mention, I use `-mllvm -constenc_prob=100`

**Comment by NeHyci** [comment]
> Forgot to mention, I use `-mllvm -constenc_prob=100`

ok...I forgot to read the source code.It seems is because we shouldn't obfuscate external linkage globalvariable, if you want to obfuscate it, add ```static```.

**Comment by NewDwarf** [comment]
Understood. Thanks for explaining...

**Comment by Naville** [comment]
That's literally 10secs of work in IDA to break lmao

**Comment by NeHyci** [comment]
> That's literally 10secs of work in IDA to break lmao

after https://github.com/NeHyci/Hikari-LLVM15-Core/commit/3403c4b6af4c19de904a5639efb18007ffedeb7b, it should no longer be destroyed by modifying segment protection, other patches are needed.
